apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bm-cluster
  namespace: infra
spec:
  project: default
  source:
    repoURL: __GITOPS_REPOSITORY_URL__
    targetRevision: main
    path: k8s
    helm:
      valuesObject: __HA_VALUES_OBJECT__
      parameters:
        - name: organizationName
          value: __ORGANIZATION_NAME_JSON__
          forceString: true
        - name: organizationSlug
          value: "__ORGANIZATION_SLUG__"
          forceString: true
        - name: gitlabGroupPath
          value: "__GITLAB_GROUP_PATH__"
          forceString: true
        - name: gitlabGroupName
          value: __GITLAB_GROUP_NAME_JSON__
          forceString: true
        - name: gitlabProjectName
          value: "__GITLAB_PROJECT_NAME__"
          forceString: true
        - name: keycloakRealm
          value: "__KEYCLOAK_REALM__"
          forceString: true
        - name: tlsSecretName
          value: "__TLS_SECRET_NAME__"
          forceString: true
        - name: sonarAlmSetting
          value: "__SONAR_ALM_SETTING__"
          forceString: true
        - name: cloudflareAccessIdpName
          value: __CLOUDFLARE_ACCESS_IDP_NAME_JSON__
          forceString: true
        - name: publicDomain
          value: __PUBLIC_DOMAIN__
        - name: internalDnsZone
          value: __INTERNAL_DNS_ZONE__
        - name: gitopsRepositoryURL
          value: __GITOPS_REPOSITORY_URL__
        - name: cloudflareAccessTeamName
          value: __CLOUDFLARE_ACCESS_TEAM_NAME__
        - name: appsEnabled
          value: "__APPS_ENABLED__"
        - name: deschedulerEnabled
          value: "__DESCHEDULER_ENABLED__"
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
  revisionHistoryLimit: 10
