apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bm-cluster
  namespace: infra
spec:
  project: default
  source:
    repoURL: __GITOPS_REPOSITORY_URL__
    targetRevision: main
    path: k8s
    helm:
      parameters:
        - name: publicDomain
          value: __PUBLIC_DOMAIN__
        - name: internalDnsZone
          value: __INTERNAL_DNS_ZONE__
        - name: gitopsRepositoryURL
          value: __GITOPS_REPOSITORY_URL__
        - name: cloudflareAccessTeamName
          value: __CLOUDFLARE_ACCESS_TEAM_NAME__
        - name: appsEnabled
          value: "__APPS_ENABLED__"
        - name: deschedulerEnabled
          value: "__DESCHEDULER_ENABLED__"
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
  revisionHistoryLimit: 10
