apiVersion: v1
kind: ConfigMap
metadata:
  name: bm-cluster-identity
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  PLATFORM_DOMAIN: "__PUBLIC_DOMAIN__"
  INTERNAL_DNS_ZONE: "__INTERNAL_DNS_ZONE__"
  ORGANIZATION_NAME: __ORGANIZATION_NAME_JSON__
  ORGANIZATION_SLUG: "__ORGANIZATION_SLUG__"
  GITLAB_GROUP_PATH: "__GITLAB_GROUP_PATH__"
  GITLAB_GROUP_NAME: __GITLAB_GROUP_NAME_JSON__
  GITLAB_PROJECT_NAME: "__GITLAB_PROJECT_NAME__"
  GITOPS_REPOSITORY_URL: "__GITOPS_REPOSITORY_URL__"
  KEYCLOAK_REALM: "__KEYCLOAK_REALM__"
  TLS_SECRET_NAME: "__TLS_SECRET_NAME__"
  SONAR_ALM_SETTING: "__SONAR_ALM_SETTING__"
  CLOUDFLARE_ACCESS_IDP_NAME: __CLOUDFLARE_ACCESS_IDP_NAME_JSON__
  CLOUDFLARE_ACCESS_TEAM_NAME: "__CLOUDFLARE_ACCESS_TEAM_NAME__"
